// flow-typed signature: 68c41cd0fce296b3296caccfe7bd8b35
// flow-typed version: <<STUB>>/@emotion/native_v^10.0.14/flow_v0.97.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@emotion/native'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@emotion/native' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@emotion/native/dist/native.browser.cjs' {
  declare module.exports: any;
}

declare module '@emotion/native/dist/native.browser.esm' {
  declare module.exports: any;
}

declare module '@emotion/native/dist/native.cjs.dev' {
  declare module.exports: any;
}

declare module '@emotion/native/dist/native.cjs' {
  declare module.exports: any;
}

declare module '@emotion/native/dist/native.cjs.prod' {
  declare module.exports: any;
}

declare module '@emotion/native/dist/native.esm' {
  declare module.exports: any;
}

declare module '@emotion/native/src/index' {
  declare module.exports: any;
}

declare module '@emotion/native/src/styled' {
  declare module.exports: any;
}

// Filename aliases
declare module '@emotion/native/dist/native.browser.cjs.js' {
  declare module.exports: $Exports<'@emotion/native/dist/native.browser.cjs'>;
}
declare module '@emotion/native/dist/native.browser.esm.js' {
  declare module.exports: $Exports<'@emotion/native/dist/native.browser.esm'>;
}
declare module '@emotion/native/dist/native.cjs.dev.js' {
  declare module.exports: $Exports<'@emotion/native/dist/native.cjs.dev'>;
}
declare module '@emotion/native/dist/native.cjs.js' {
  declare module.exports: $Exports<'@emotion/native/dist/native.cjs'>;
}
declare module '@emotion/native/dist/native.cjs.prod.js' {
  declare module.exports: $Exports<'@emotion/native/dist/native.cjs.prod'>;
}
declare module '@emotion/native/dist/native.esm.js' {
  declare module.exports: $Exports<'@emotion/native/dist/native.esm'>;
}
declare module '@emotion/native/src/index.js' {
  declare module.exports: $Exports<'@emotion/native/src/index'>;
}
declare module '@emotion/native/src/styled.js' {
  declare module.exports: $Exports<'@emotion/native/src/styled'>;
}
