// flow-typed signature: d8c2867eba078a089019ab4e7cb783d6
// flow-typed version: <<STUB>>/appcenter-analytics_v^1.3.0/flow_v0.66.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'appcenter-analytics'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'appcenter-analytics' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'appcenter-analytics/Analytics' {
  declare module.exports: any;
}

declare module 'appcenter-analytics/scripts/postlink' {
  declare module.exports: any;
}

declare module 'appcenter-analytics/scripts/prelink' {
  declare module.exports: any;
}

// Filename aliases
declare module 'appcenter-analytics/Analytics.js' {
  declare module.exports: $Exports<'appcenter-analytics/Analytics'>;
}
declare module 'appcenter-analytics/scripts/postlink.js' {
  declare module.exports: $Exports<'appcenter-analytics/scripts/postlink'>;
}
declare module 'appcenter-analytics/scripts/prelink.js' {
  declare module.exports: $Exports<'appcenter-analytics/scripts/prelink'>;
}
