// flow-typed signature: 50cb111119bb9c7153b145cf8425b0ad
// flow-typed version: <<STUB>>/expo-linear-gradient_v^5.0.1/flow_v0.97.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'expo-linear-gradient'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'expo-linear-gradient' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'expo-linear-gradient/build/index' {
  declare module.exports: any;
}

declare module 'expo-linear-gradient/build/LinearGradient' {
  declare module.exports: any;
}

declare module 'expo-linear-gradient/build/NativeLinearGradient.android' {
  declare module.exports: any;
}

declare module 'expo-linear-gradient/build/NativeLinearGradient.ios' {
  declare module.exports: any;
}

declare module 'expo-linear-gradient/build/NativeLinearGradient.web' {
  declare module.exports: any;
}

// Filename aliases
declare module 'expo-linear-gradient/build/index.js' {
  declare module.exports: $Exports<'expo-linear-gradient/build/index'>;
}
declare module 'expo-linear-gradient/build/LinearGradient.js' {
  declare module.exports: $Exports<'expo-linear-gradient/build/LinearGradient'>;
}
declare module 'expo-linear-gradient/build/NativeLinearGradient.android.js' {
  declare module.exports: $Exports<'expo-linear-gradient/build/NativeLinearGradient.android'>;
}
declare module 'expo-linear-gradient/build/NativeLinearGradient.ios.js' {
  declare module.exports: $Exports<'expo-linear-gradient/build/NativeLinearGradient.ios'>;
}
declare module 'expo-linear-gradient/build/NativeLinearGradient.web.js' {
  declare module.exports: $Exports<'expo-linear-gradient/build/NativeLinearGradient.web'>;
}
