// flow-typed signature: e587f07cd8f77875b2f1e62cc590108b
// flow-typed version: <<STUB>>/jsc-android_v^241213.1.0/flow_v0.97.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jsc-android'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'jsc-android' {
  declare module.exports: any;
}
