// flow-typed signature: 4049abf9b64ea35531ecd802932f6370
// flow-typed version: <<STUB>>/jsc-android_v^236355.1.1/flow_v0.97.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jsc-android'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'jsc-android' {
  declare module.exports: any;
}
