// flow-typed signature: 6e96edd9c7209a8aecbba7fd94c01815
// flow-typed version: <<STUB>>/loki_v^0.14.2/flow_v0.97.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'loki'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'loki' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'loki/configure-react-native' {
  declare module.exports: any;
}

declare module 'loki/configure-react' {
  declare module.exports: any;
}

declare module 'loki/configure-vue' {
  declare module.exports: any;
}

declare module 'loki/src/build-command' {
  declare module.exports: any;
}

declare module 'loki/src/cli' {
  declare module.exports: any;
}

declare module 'loki/src/commands/approve/index' {
  declare module.exports: any;
}

declare module 'loki/src/commands/approve/parse-options' {
  declare module.exports: any;
}

declare module 'loki/src/commands/init/index' {
  declare module.exports: any;
}

declare module 'loki/src/commands/test/get-absolute-url' {
  declare module.exports: any;
}

declare module 'loki/src/commands/test/index' {
  declare module.exports: any;
}

declare module 'loki/src/commands/test/parse-options' {
  declare module.exports: any;
}

declare module 'loki/src/commands/test/run-tests' {
  declare module.exports: any;
}

declare module 'loki/src/commands/test/test-story' {
  declare module.exports: any;
}

declare module 'loki/src/config/get-defaults' {
  declare module.exports: any;
}

declare module 'loki/src/config/index' {
  declare module.exports: any;
}

declare module 'loki/src/config/project-package' {
  declare module.exports: any;
}

declare module 'loki/src/console' {
  declare module.exports: any;
}

declare module 'loki/src/dependency-detection' {
  declare module.exports: any;
}

declare module 'loki/src/diffing/gm' {
  declare module.exports: any;
}

declare module 'loki/src/diffing/index' {
  declare module.exports: any;
}

declare module 'loki/src/diffing/looks-same' {
  declare module.exports: any;
}

declare module 'loki/src/errors' {
  declare module.exports: any;
}

declare module 'loki/src/failure-handling' {
  declare module.exports: any;
}

declare module 'loki/src/targets/chrome/app' {
  declare module.exports: any;
}

declare module 'loki/src/targets/chrome/await-loki-ready' {
  declare module.exports: any;
}

declare module 'loki/src/targets/chrome/configure-react-storybook' {
  declare module.exports: any;
}

declare module 'loki/src/targets/chrome/configure-storybook' {
  declare module.exports: any;
}

declare module 'loki/src/targets/chrome/configure-vue-storybook' {
  declare module.exports: any;
}

declare module 'loki/src/targets/chrome/create-chrome-target' {
  declare module.exports: any;
}

declare module 'loki/src/targets/chrome/disable-animations' {
  declare module.exports: any;
}

declare module 'loki/src/targets/chrome/docker' {
  declare module.exports: any;
}

declare module 'loki/src/targets/chrome/get-selector-box-size' {
  declare module.exports: any;
}

declare module 'loki/src/targets/chrome/get-stories' {
  declare module.exports: any;
}

declare module 'loki/src/targets/chrome/index' {
  declare module.exports: any;
}

declare module 'loki/src/targets/decorate-storybook' {
  declare module.exports: any;
}

declare module 'loki/src/targets/index' {
  declare module.exports: any;
}

declare module 'loki/src/targets/native/android-emulator' {
  declare module.exports: any;
}

declare module 'loki/src/targets/native/configure-storybook' {
  declare module.exports: any;
}

declare module 'loki/src/targets/native/create-message-queue' {
  declare module.exports: any;
}

declare module 'loki/src/targets/native/create-websocket-target' {
  declare module.exports: any;
}

declare module 'loki/src/targets/native/index' {
  declare module.exports: any;
}

declare module 'loki/src/targets/native/ios-simulator' {
  declare module.exports: any;
}

declare module 'loki/src/targets/native/ready-state-emitting-image' {
  declare module.exports: any;
}

declare module 'loki/src/targets/ready-state-manager' {
  declare module.exports: any;
}

// Filename aliases
declare module 'loki/configure-react-native.js' {
  declare module.exports: $Exports<'loki/configure-react-native'>;
}
declare module 'loki/configure-react.js' {
  declare module.exports: $Exports<'loki/configure-react'>;
}
declare module 'loki/configure-vue.js' {
  declare module.exports: $Exports<'loki/configure-vue'>;
}
declare module 'loki/src/build-command.js' {
  declare module.exports: $Exports<'loki/src/build-command'>;
}
declare module 'loki/src/cli.js' {
  declare module.exports: $Exports<'loki/src/cli'>;
}
declare module 'loki/src/commands/approve/index.js' {
  declare module.exports: $Exports<'loki/src/commands/approve/index'>;
}
declare module 'loki/src/commands/approve/parse-options.js' {
  declare module.exports: $Exports<'loki/src/commands/approve/parse-options'>;
}
declare module 'loki/src/commands/init/index.js' {
  declare module.exports: $Exports<'loki/src/commands/init/index'>;
}
declare module 'loki/src/commands/test/get-absolute-url.js' {
  declare module.exports: $Exports<'loki/src/commands/test/get-absolute-url'>;
}
declare module 'loki/src/commands/test/index.js' {
  declare module.exports: $Exports<'loki/src/commands/test/index'>;
}
declare module 'loki/src/commands/test/parse-options.js' {
  declare module.exports: $Exports<'loki/src/commands/test/parse-options'>;
}
declare module 'loki/src/commands/test/run-tests.js' {
  declare module.exports: $Exports<'loki/src/commands/test/run-tests'>;
}
declare module 'loki/src/commands/test/test-story.js' {
  declare module.exports: $Exports<'loki/src/commands/test/test-story'>;
}
declare module 'loki/src/config/get-defaults.js' {
  declare module.exports: $Exports<'loki/src/config/get-defaults'>;
}
declare module 'loki/src/config/index.js' {
  declare module.exports: $Exports<'loki/src/config/index'>;
}
declare module 'loki/src/config/project-package.js' {
  declare module.exports: $Exports<'loki/src/config/project-package'>;
}
declare module 'loki/src/console.js' {
  declare module.exports: $Exports<'loki/src/console'>;
}
declare module 'loki/src/dependency-detection.js' {
  declare module.exports: $Exports<'loki/src/dependency-detection'>;
}
declare module 'loki/src/diffing/gm.js' {
  declare module.exports: $Exports<'loki/src/diffing/gm'>;
}
declare module 'loki/src/diffing/index.js' {
  declare module.exports: $Exports<'loki/src/diffing/index'>;
}
declare module 'loki/src/diffing/looks-same.js' {
  declare module.exports: $Exports<'loki/src/diffing/looks-same'>;
}
declare module 'loki/src/errors.js' {
  declare module.exports: $Exports<'loki/src/errors'>;
}
declare module 'loki/src/failure-handling.js' {
  declare module.exports: $Exports<'loki/src/failure-handling'>;
}
declare module 'loki/src/targets/chrome/app.js' {
  declare module.exports: $Exports<'loki/src/targets/chrome/app'>;
}
declare module 'loki/src/targets/chrome/await-loki-ready.js' {
  declare module.exports: $Exports<'loki/src/targets/chrome/await-loki-ready'>;
}
declare module 'loki/src/targets/chrome/configure-react-storybook.js' {
  declare module.exports: $Exports<'loki/src/targets/chrome/configure-react-storybook'>;
}
declare module 'loki/src/targets/chrome/configure-storybook.js' {
  declare module.exports: $Exports<'loki/src/targets/chrome/configure-storybook'>;
}
declare module 'loki/src/targets/chrome/configure-vue-storybook.js' {
  declare module.exports: $Exports<'loki/src/targets/chrome/configure-vue-storybook'>;
}
declare module 'loki/src/targets/chrome/create-chrome-target.js' {
  declare module.exports: $Exports<'loki/src/targets/chrome/create-chrome-target'>;
}
declare module 'loki/src/targets/chrome/disable-animations.js' {
  declare module.exports: $Exports<'loki/src/targets/chrome/disable-animations'>;
}
declare module 'loki/src/targets/chrome/docker.js' {
  declare module.exports: $Exports<'loki/src/targets/chrome/docker'>;
}
declare module 'loki/src/targets/chrome/get-selector-box-size.js' {
  declare module.exports: $Exports<'loki/src/targets/chrome/get-selector-box-size'>;
}
declare module 'loki/src/targets/chrome/get-stories.js' {
  declare module.exports: $Exports<'loki/src/targets/chrome/get-stories'>;
}
declare module 'loki/src/targets/chrome/index.js' {
  declare module.exports: $Exports<'loki/src/targets/chrome/index'>;
}
declare module 'loki/src/targets/decorate-storybook.js' {
  declare module.exports: $Exports<'loki/src/targets/decorate-storybook'>;
}
declare module 'loki/src/targets/index.js' {
  declare module.exports: $Exports<'loki/src/targets/index'>;
}
declare module 'loki/src/targets/native/android-emulator.js' {
  declare module.exports: $Exports<'loki/src/targets/native/android-emulator'>;
}
declare module 'loki/src/targets/native/configure-storybook.js' {
  declare module.exports: $Exports<'loki/src/targets/native/configure-storybook'>;
}
declare module 'loki/src/targets/native/create-message-queue.js' {
  declare module.exports: $Exports<'loki/src/targets/native/create-message-queue'>;
}
declare module 'loki/src/targets/native/create-websocket-target.js' {
  declare module.exports: $Exports<'loki/src/targets/native/create-websocket-target'>;
}
declare module 'loki/src/targets/native/index.js' {
  declare module.exports: $Exports<'loki/src/targets/native/index'>;
}
declare module 'loki/src/targets/native/ios-simulator.js' {
  declare module.exports: $Exports<'loki/src/targets/native/ios-simulator'>;
}
declare module 'loki/src/targets/native/ready-state-emitting-image.js' {
  declare module.exports: $Exports<'loki/src/targets/native/ready-state-emitting-image'>;
}
declare module 'loki/src/targets/ready-state-manager.js' {
  declare module.exports: $Exports<'loki/src/targets/ready-state-manager'>;
}
