// flow-typed signature: 03d75ef543a1108526b6e4f8f0ee5e5e
// flow-typed version: <<STUB>>/react-native-contacts_v^4.0.2/flow_v0.97.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-contacts'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-contacts' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-contacts/example/__tests__/App-test' {
  declare module.exports: any;
}

declare module 'react-native-contacts/example/App' {
  declare module.exports: any;
}

declare module 'react-native-contacts/example/babel.config' {
  declare module.exports: any;
}

declare module 'react-native-contacts/example/index' {
  declare module.exports: any;
}

declare module 'react-native-contacts/example/metro.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-contacts/example/__tests__/App-test.js' {
  declare module.exports: $Exports<'react-native-contacts/example/__tests__/App-test'>;
}
declare module 'react-native-contacts/example/App.js' {
  declare module.exports: $Exports<'react-native-contacts/example/App'>;
}
declare module 'react-native-contacts/example/babel.config.js' {
  declare module.exports: $Exports<'react-native-contacts/example/babel.config'>;
}
declare module 'react-native-contacts/example/index.js' {
  declare module.exports: $Exports<'react-native-contacts/example/index'>;
}
declare module 'react-native-contacts/example/metro.config.js' {
  declare module.exports: $Exports<'react-native-contacts/example/metro.config'>;
}
declare module 'react-native-contacts/index' {
  declare module.exports: $Exports<'react-native-contacts'>;
}
declare module 'react-native-contacts/index.js' {
  declare module.exports: $Exports<'react-native-contacts'>;
}
