// flow-typed signature: e9c4fac1f5ce36237d721f2e7ae95d20
// flow-typed version: <<STUB>>/react-native-country-picker-modal_v^0.7.1/flow_v0.97.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-country-picker-modal'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-country-picker-modal' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-country-picker-modal/__tests__/CountryPickerTests' {
  declare module.exports: any;
}

declare module 'react-native-country-picker-modal/src/CloseButton.android' {
  declare module.exports: any;
}

declare module 'react-native-country-picker-modal/src/CloseButton.ios' {
  declare module.exports: any;
}

declare module 'react-native-country-picker-modal/src/countryFlags' {
  declare module.exports: any;
}

declare module 'react-native-country-picker-modal/src/CountryPicker' {
  declare module.exports: any;
}

declare module 'react-native-country-picker-modal/src/CountryPicker.style' {
  declare module.exports: any;
}

declare module 'react-native-country-picker-modal/src/emoji' {
  declare module.exports: any;
}

declare module 'react-native-country-picker-modal/src/KeyboardAvoidingView.android' {
  declare module.exports: any;
}

declare module 'react-native-country-picker-modal/src/KeyboardAvoidingView.ios' {
  declare module.exports: any;
}

declare module 'react-native-country-picker-modal/src/ratio' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-country-picker-modal/__tests__/CountryPickerTests.js' {
  declare module.exports: $Exports<'react-native-country-picker-modal/__tests__/CountryPickerTests'>;
}
declare module 'react-native-country-picker-modal/src/CloseButton.android.js' {
  declare module.exports: $Exports<'react-native-country-picker-modal/src/CloseButton.android'>;
}
declare module 'react-native-country-picker-modal/src/CloseButton.ios.js' {
  declare module.exports: $Exports<'react-native-country-picker-modal/src/CloseButton.ios'>;
}
declare module 'react-native-country-picker-modal/src/countryFlags.js' {
  declare module.exports: $Exports<'react-native-country-picker-modal/src/countryFlags'>;
}
declare module 'react-native-country-picker-modal/src/CountryPicker.js' {
  declare module.exports: $Exports<'react-native-country-picker-modal/src/CountryPicker'>;
}
declare module 'react-native-country-picker-modal/src/CountryPicker.style.js' {
  declare module.exports: $Exports<'react-native-country-picker-modal/src/CountryPicker.style'>;
}
declare module 'react-native-country-picker-modal/src/emoji.js' {
  declare module.exports: $Exports<'react-native-country-picker-modal/src/emoji'>;
}
declare module 'react-native-country-picker-modal/src/KeyboardAvoidingView.android.js' {
  declare module.exports: $Exports<'react-native-country-picker-modal/src/KeyboardAvoidingView.android'>;
}
declare module 'react-native-country-picker-modal/src/KeyboardAvoidingView.ios.js' {
  declare module.exports: $Exports<'react-native-country-picker-modal/src/KeyboardAvoidingView.ios'>;
}
declare module 'react-native-country-picker-modal/src/ratio.js' {
  declare module.exports: $Exports<'react-native-country-picker-modal/src/ratio'>;
}
