// flow-typed signature: e4b5baf0827249a2ca69f9ac34c76d14
// flow-typed version: <<STUB>>/react-native-radial-gradient_v^1.0.5/flow_v0.97.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-radial-gradient'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-radial-gradient' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'react-native-radial-gradient/index' {
  declare module.exports: $Exports<'react-native-radial-gradient'>;
}
declare module 'react-native-radial-gradient/index.js' {
  declare module.exports: $Exports<'react-native-radial-gradient'>;
}
