// flow-typed signature: e87f7af159f352b4a5fa6d960fc906e2
// flow-typed version: <<STUB>>/redux-saga_v1.0.2/flow_v0.97.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'redux-saga'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'redux-saga' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'redux-saga/dist/chunk-b03f85c9' {
  declare module.exports: any;
}

declare module 'redux-saga/dist/redux-saga-core-npm-proxy.cjs' {
  declare module.exports: any;
}

declare module 'redux-saga/dist/redux-saga-core-npm-proxy.esm' {
  declare module.exports: any;
}

declare module 'redux-saga/dist/redux-saga-core.esmodules-browsers' {
  declare module.exports: any;
}

declare module 'redux-saga/dist/redux-saga-effects-npm-proxy.cjs' {
  declare module.exports: any;
}

declare module 'redux-saga/dist/redux-saga-effects-npm-proxy.esm' {
  declare module.exports: any;
}

declare module 'redux-saga/dist/redux-saga-effects.esmodules-browsers' {
  declare module.exports: any;
}

declare module 'redux-saga/dist/redux-saga.umd' {
  declare module.exports: any;
}

declare module 'redux-saga/dist/redux-saga.umd.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'redux-saga/dist/chunk-b03f85c9.js' {
  declare module.exports: $Exports<'redux-saga/dist/chunk-b03f85c9'>;
}
declare module 'redux-saga/dist/redux-saga-core-npm-proxy.cjs.js' {
  declare module.exports: $Exports<'redux-saga/dist/redux-saga-core-npm-proxy.cjs'>;
}
declare module 'redux-saga/dist/redux-saga-core-npm-proxy.esm.js' {
  declare module.exports: $Exports<'redux-saga/dist/redux-saga-core-npm-proxy.esm'>;
}
declare module 'redux-saga/dist/redux-saga-core.esmodules-browsers.js' {
  declare module.exports: $Exports<'redux-saga/dist/redux-saga-core.esmodules-browsers'>;
}
declare module 'redux-saga/dist/redux-saga-effects-npm-proxy.cjs.js' {
  declare module.exports: $Exports<'redux-saga/dist/redux-saga-effects-npm-proxy.cjs'>;
}
declare module 'redux-saga/dist/redux-saga-effects-npm-proxy.esm.js' {
  declare module.exports: $Exports<'redux-saga/dist/redux-saga-effects-npm-proxy.esm'>;
}
declare module 'redux-saga/dist/redux-saga-effects.esmodules-browsers.js' {
  declare module.exports: $Exports<'redux-saga/dist/redux-saga-effects.esmodules-browsers'>;
}
declare module 'redux-saga/dist/redux-saga.umd.js' {
  declare module.exports: $Exports<'redux-saga/dist/redux-saga.umd'>;
}
declare module 'redux-saga/dist/redux-saga.umd.min.js' {
  declare module.exports: $Exports<'redux-saga/dist/redux-saga.umd.min'>;
}
