// flow-typed signature: 9dfca0a32cae6a41e971885ad7100ef4
// flow-typed version: <<STUB>>/tcomb-form-native_v^0.6.20/flow_v0.97.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'tcomb-form-native'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'tcomb-form-native' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'tcomb-form-native/lib/components' {
  declare module.exports: any;
}

declare module 'tcomb-form-native/lib/i18n/en' {
  declare module.exports: any;
}

declare module 'tcomb-form-native/lib/index' {
  declare module.exports: any;
}

declare module 'tcomb-form-native/lib/stylesheets/bootstrap' {
  declare module.exports: any;
}

declare module 'tcomb-form-native/lib/templates/bootstrap/checkbox' {
  declare module.exports: any;
}

declare module 'tcomb-form-native/lib/templates/bootstrap/datepicker.android' {
  declare module.exports: any;
}

declare module 'tcomb-form-native/lib/templates/bootstrap/datepicker.ios' {
  declare module.exports: any;
}

declare module 'tcomb-form-native/lib/templates/bootstrap/index' {
  declare module.exports: any;
}

declare module 'tcomb-form-native/lib/templates/bootstrap/list' {
  declare module.exports: any;
}

declare module 'tcomb-form-native/lib/templates/bootstrap/select.android' {
  declare module.exports: any;
}

declare module 'tcomb-form-native/lib/templates/bootstrap/select.ios' {
  declare module.exports: any;
}

declare module 'tcomb-form-native/lib/templates/bootstrap/struct' {
  declare module.exports: any;
}

declare module 'tcomb-form-native/lib/templates/bootstrap/textbox' {
  declare module.exports: any;
}

declare module 'tcomb-form-native/lib/util' {
  declare module.exports: any;
}

// Filename aliases
declare module 'tcomb-form-native/index' {
  declare module.exports: $Exports<'tcomb-form-native'>;
}
declare module 'tcomb-form-native/index.js' {
  declare module.exports: $Exports<'tcomb-form-native'>;
}
declare module 'tcomb-form-native/lib/components.js' {
  declare module.exports: $Exports<'tcomb-form-native/lib/components'>;
}
declare module 'tcomb-form-native/lib/i18n/en.js' {
  declare module.exports: $Exports<'tcomb-form-native/lib/i18n/en'>;
}
declare module 'tcomb-form-native/lib/index.js' {
  declare module.exports: $Exports<'tcomb-form-native/lib/index'>;
}
declare module 'tcomb-form-native/lib/stylesheets/bootstrap.js' {
  declare module.exports: $Exports<'tcomb-form-native/lib/stylesheets/bootstrap'>;
}
declare module 'tcomb-form-native/lib/templates/bootstrap/checkbox.js' {
  declare module.exports: $Exports<'tcomb-form-native/lib/templates/bootstrap/checkbox'>;
}
declare module 'tcomb-form-native/lib/templates/bootstrap/datepicker.android.js' {
  declare module.exports: $Exports<'tcomb-form-native/lib/templates/bootstrap/datepicker.android'>;
}
declare module 'tcomb-form-native/lib/templates/bootstrap/datepicker.ios.js' {
  declare module.exports: $Exports<'tcomb-form-native/lib/templates/bootstrap/datepicker.ios'>;
}
declare module 'tcomb-form-native/lib/templates/bootstrap/index.js' {
  declare module.exports: $Exports<'tcomb-form-native/lib/templates/bootstrap/index'>;
}
declare module 'tcomb-form-native/lib/templates/bootstrap/list.js' {
  declare module.exports: $Exports<'tcomb-form-native/lib/templates/bootstrap/list'>;
}
declare module 'tcomb-form-native/lib/templates/bootstrap/select.android.js' {
  declare module.exports: $Exports<'tcomb-form-native/lib/templates/bootstrap/select.android'>;
}
declare module 'tcomb-form-native/lib/templates/bootstrap/select.ios.js' {
  declare module.exports: $Exports<'tcomb-form-native/lib/templates/bootstrap/select.ios'>;
}
declare module 'tcomb-form-native/lib/templates/bootstrap/struct.js' {
  declare module.exports: $Exports<'tcomb-form-native/lib/templates/bootstrap/struct'>;
}
declare module 'tcomb-form-native/lib/templates/bootstrap/textbox.js' {
  declare module.exports: $Exports<'tcomb-form-native/lib/templates/bootstrap/textbox'>;
}
declare module 'tcomb-form-native/lib/util.js' {
  declare module.exports: $Exports<'tcomb-form-native/lib/util'>;
}
