version: 2
defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/node:10.10.0
jobs:
  build:
    <<: *defaults
    steps:
      - checkout

      - restore_cache:
          key: yarn-v1-{{ checksum "yarn.lock" }}-{{ arch }}

      - restore_cache:
          key: node-v1-{{ checksum "package.json" }}-{{ arch }}

      - run: yarn install

      - save_cache:
          key: yarn-v1-{{ checksum "yarn.lock" }}-{{ arch }}
          paths:
            - ~/.cache/yarn

      - save_cache:
          key: node-v1-{{ checksum "package.json" }}-{{ arch }}
          paths:
            - node_modules

      # Run eslint
      - run: yarn lint

      # Run flow
      - run: yarn flow

      # Run coverage
      - run: yarn coverage --runInBand

workflows:
  version: 2
  eslint-flow-converage:
    jobs:
      - build