// flow-typed signature: 5cce7bda1478a35ec5129fafe725dec6
// flow-typed version: <<STUB>>/@kevinwolf/formal-native_v^0.1.1/flow_v0.97.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@kevinwolf/formal-native'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@kevinwolf/formal-native' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@kevinwolf/formal-native/lib/formal-native' {
  declare module.exports: any;
}

declare module '@kevinwolf/formal-native/lib/types' {
  declare module.exports: any;
}

declare module '@kevinwolf/formal-native/lib/use-formal-native' {
  declare module.exports: any;
}

// Filename aliases
declare module '@kevinwolf/formal-native/lib/formal-native.js' {
  declare module.exports: $Exports<'@kevinwolf/formal-native/lib/formal-native'>;
}
declare module '@kevinwolf/formal-native/lib/types.js' {
  declare module.exports: $Exports<'@kevinwolf/formal-native/lib/types'>;
}
declare module '@kevinwolf/formal-native/lib/use-formal-native.js' {
  declare module.exports: $Exports<'@kevinwolf/formal-native/lib/use-formal-native'>;
}
