platform :ios, '9.0'

def shared_pods
  pod 'AppCenter/Crashes'
  pod 'AppCenter/Analytics'
  pod 'AppCenterReactNativeShared'
end

target 'ReactNativeSeed' do
  shared_pods
end

target 'ReactNativeSeed Debug' do
  shared_pods
end

target 'ReactNativeSeed Staging' do
  shared_pods
end
