platform :ios, '9.0'

def shared_pods
  # Pods for AppCenter
  pod 'AppCenterReactNativeShared', '~> 2.0.0'
  pod 'AppCenter/Analytics', '~> 2.0.1'
end

target 'UpdateAdd' do
  shared_pods
end

target 'UpdateAdd Debug' do
  shared_pods
end

target 'UpdateAdd Staging' do
  shared_pods
end
