platform :ios, '9.0'

def shared_pods
  # Pods for AppCenter
  pod 'AppCenterReactNativeShared', '~> 2.0.0'
  pod 'AppCenter/Analytics', '~> 2.0.1'
end

target 'ReactNativeSeed' do
  shared_pods
end

target 'ReactNativeSeed Debug' do
  shared_pods
end

target 'ReactNativeSeed Staging' do
  shared_pods
end
