// flow-typed signature: a4b727ed369ca8844fd9ef36ce57b1e5
// flow-typed version: <<STUB>>/@storybook/addon-ondevice-knobs_v^4.0.12/flow_v0.87.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@storybook/addon-ondevice-knobs'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@storybook/addon-ondevice-knobs' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@storybook/addon-ondevice-knobs/dist/GroupTabs' {
  declare module.exports: any;
}

declare module '@storybook/addon-ondevice-knobs/dist/index' {
  declare module.exports: any;
}

declare module '@storybook/addon-ondevice-knobs/dist/panel' {
  declare module.exports: any;
}

declare module '@storybook/addon-ondevice-knobs/dist/PropField' {
  declare module.exports: any;
}

declare module '@storybook/addon-ondevice-knobs/dist/PropForm' {
  declare module.exports: any;
}

declare module '@storybook/addon-ondevice-knobs/dist/types/Array' {
  declare module.exports: any;
}

declare module '@storybook/addon-ondevice-knobs/dist/types/Boolean' {
  declare module.exports: any;
}

declare module '@storybook/addon-ondevice-knobs/dist/types/Button' {
  declare module.exports: any;
}

declare module '@storybook/addon-ondevice-knobs/dist/types/Color' {
  declare module.exports: any;
}

declare module '@storybook/addon-ondevice-knobs/dist/types/Date' {
  declare module.exports: any;
}

declare module '@storybook/addon-ondevice-knobs/dist/types/index' {
  declare module.exports: any;
}

declare module '@storybook/addon-ondevice-knobs/dist/types/Number' {
  declare module.exports: any;
}

declare module '@storybook/addon-ondevice-knobs/dist/types/Object' {
  declare module.exports: any;
}

declare module '@storybook/addon-ondevice-knobs/dist/types/Select' {
  declare module.exports: any;
}

declare module '@storybook/addon-ondevice-knobs/dist/types/Text' {
  declare module.exports: any;
}

declare module '@storybook/addon-ondevice-knobs/register' {
  declare module.exports: any;
}

declare module '@storybook/addon-ondevice-knobs/src/GroupTabs' {
  declare module.exports: any;
}

declare module '@storybook/addon-ondevice-knobs/src/index' {
  declare module.exports: any;
}

declare module '@storybook/addon-ondevice-knobs/src/panel' {
  declare module.exports: any;
}

declare module '@storybook/addon-ondevice-knobs/src/PropField' {
  declare module.exports: any;
}

declare module '@storybook/addon-ondevice-knobs/src/PropForm' {
  declare module.exports: any;
}

declare module '@storybook/addon-ondevice-knobs/src/types/Array' {
  declare module.exports: any;
}

declare module '@storybook/addon-ondevice-knobs/src/types/Boolean' {
  declare module.exports: any;
}

declare module '@storybook/addon-ondevice-knobs/src/types/Button' {
  declare module.exports: any;
}

declare module '@storybook/addon-ondevice-knobs/src/types/Color' {
  declare module.exports: any;
}

declare module '@storybook/addon-ondevice-knobs/src/types/Date' {
  declare module.exports: any;
}

declare module '@storybook/addon-ondevice-knobs/src/types/index' {
  declare module.exports: any;
}

declare module '@storybook/addon-ondevice-knobs/src/types/Number' {
  declare module.exports: any;
}

declare module '@storybook/addon-ondevice-knobs/src/types/Object' {
  declare module.exports: any;
}

declare module '@storybook/addon-ondevice-knobs/src/types/Select' {
  declare module.exports: any;
}

declare module '@storybook/addon-ondevice-knobs/src/types/Text' {
  declare module.exports: any;
}

// Filename aliases
declare module '@storybook/addon-ondevice-knobs/dist/GroupTabs.js' {
  declare module.exports: $Exports<'@storybook/addon-ondevice-knobs/dist/GroupTabs'>;
}
declare module '@storybook/addon-ondevice-knobs/dist/index.js' {
  declare module.exports: $Exports<'@storybook/addon-ondevice-knobs/dist/index'>;
}
declare module '@storybook/addon-ondevice-knobs/dist/panel.js' {
  declare module.exports: $Exports<'@storybook/addon-ondevice-knobs/dist/panel'>;
}
declare module '@storybook/addon-ondevice-knobs/dist/PropField.js' {
  declare module.exports: $Exports<'@storybook/addon-ondevice-knobs/dist/PropField'>;
}
declare module '@storybook/addon-ondevice-knobs/dist/PropForm.js' {
  declare module.exports: $Exports<'@storybook/addon-ondevice-knobs/dist/PropForm'>;
}
declare module '@storybook/addon-ondevice-knobs/dist/types/Array.js' {
  declare module.exports: $Exports<'@storybook/addon-ondevice-knobs/dist/types/Array'>;
}
declare module '@storybook/addon-ondevice-knobs/dist/types/Boolean.js' {
  declare module.exports: $Exports<'@storybook/addon-ondevice-knobs/dist/types/Boolean'>;
}
declare module '@storybook/addon-ondevice-knobs/dist/types/Button.js' {
  declare module.exports: $Exports<'@storybook/addon-ondevice-knobs/dist/types/Button'>;
}
declare module '@storybook/addon-ondevice-knobs/dist/types/Color.js' {
  declare module.exports: $Exports<'@storybook/addon-ondevice-knobs/dist/types/Color'>;
}
declare module '@storybook/addon-ondevice-knobs/dist/types/Date.js' {
  declare module.exports: $Exports<'@storybook/addon-ondevice-knobs/dist/types/Date'>;
}
declare module '@storybook/addon-ondevice-knobs/dist/types/index.js' {
  declare module.exports: $Exports<'@storybook/addon-ondevice-knobs/dist/types/index'>;
}
declare module '@storybook/addon-ondevice-knobs/dist/types/Number.js' {
  declare module.exports: $Exports<'@storybook/addon-ondevice-knobs/dist/types/Number'>;
}
declare module '@storybook/addon-ondevice-knobs/dist/types/Object.js' {
  declare module.exports: $Exports<'@storybook/addon-ondevice-knobs/dist/types/Object'>;
}
declare module '@storybook/addon-ondevice-knobs/dist/types/Select.js' {
  declare module.exports: $Exports<'@storybook/addon-ondevice-knobs/dist/types/Select'>;
}
declare module '@storybook/addon-ondevice-knobs/dist/types/Text.js' {
  declare module.exports: $Exports<'@storybook/addon-ondevice-knobs/dist/types/Text'>;
}
declare module '@storybook/addon-ondevice-knobs/register.js' {
  declare module.exports: $Exports<'@storybook/addon-ondevice-knobs/register'>;
}
declare module '@storybook/addon-ondevice-knobs/src/GroupTabs.js' {
  declare module.exports: $Exports<'@storybook/addon-ondevice-knobs/src/GroupTabs'>;
}
declare module '@storybook/addon-ondevice-knobs/src/index.js' {
  declare module.exports: $Exports<'@storybook/addon-ondevice-knobs/src/index'>;
}
declare module '@storybook/addon-ondevice-knobs/src/panel.js' {
  declare module.exports: $Exports<'@storybook/addon-ondevice-knobs/src/panel'>;
}
declare module '@storybook/addon-ondevice-knobs/src/PropField.js' {
  declare module.exports: $Exports<'@storybook/addon-ondevice-knobs/src/PropField'>;
}
declare module '@storybook/addon-ondevice-knobs/src/PropForm.js' {
  declare module.exports: $Exports<'@storybook/addon-ondevice-knobs/src/PropForm'>;
}
declare module '@storybook/addon-ondevice-knobs/src/types/Array.js' {
  declare module.exports: $Exports<'@storybook/addon-ondevice-knobs/src/types/Array'>;
}
declare module '@storybook/addon-ondevice-knobs/src/types/Boolean.js' {
  declare module.exports: $Exports<'@storybook/addon-ondevice-knobs/src/types/Boolean'>;
}
declare module '@storybook/addon-ondevice-knobs/src/types/Button.js' {
  declare module.exports: $Exports<'@storybook/addon-ondevice-knobs/src/types/Button'>;
}
declare module '@storybook/addon-ondevice-knobs/src/types/Color.js' {
  declare module.exports: $Exports<'@storybook/addon-ondevice-knobs/src/types/Color'>;
}
declare module '@storybook/addon-ondevice-knobs/src/types/Date.js' {
  declare module.exports: $Exports<'@storybook/addon-ondevice-knobs/src/types/Date'>;
}
declare module '@storybook/addon-ondevice-knobs/src/types/index.js' {
  declare module.exports: $Exports<'@storybook/addon-ondevice-knobs/src/types/index'>;
}
declare module '@storybook/addon-ondevice-knobs/src/types/Number.js' {
  declare module.exports: $Exports<'@storybook/addon-ondevice-knobs/src/types/Number'>;
}
declare module '@storybook/addon-ondevice-knobs/src/types/Object.js' {
  declare module.exports: $Exports<'@storybook/addon-ondevice-knobs/src/types/Object'>;
}
declare module '@storybook/addon-ondevice-knobs/src/types/Select.js' {
  declare module.exports: $Exports<'@storybook/addon-ondevice-knobs/src/types/Select'>;
}
declare module '@storybook/addon-ondevice-knobs/src/types/Text.js' {
  declare module.exports: $Exports<'@storybook/addon-ondevice-knobs/src/types/Text'>;
}
