// flow-typed signature: 26e09d421509e7015baa33a06c2d4210
// flow-typed version: <<STUB>>/@storybook/addon-a11y_v^4.0.2/flow_v0.87.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@storybook/addon-a11y'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@storybook/addon-a11y' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@storybook/addon-a11y/dist/components/Panel' {
  declare module.exports: any;
}

declare module '@storybook/addon-a11y/dist/components/Report/Elements' {
  declare module.exports: any;
}

declare module '@storybook/addon-a11y/dist/components/Report/index' {
  declare module.exports: any;
}

declare module '@storybook/addon-a11y/dist/components/Report/Info' {
  declare module.exports: any;
}

declare module '@storybook/addon-a11y/dist/components/Report/Item' {
  declare module.exports: any;
}

declare module '@storybook/addon-a11y/dist/components/Report/Rules' {
  declare module.exports: any;
}

declare module '@storybook/addon-a11y/dist/components/Report/Tags' {
  declare module.exports: any;
}

declare module '@storybook/addon-a11y/dist/components/Tabs' {
  declare module.exports: any;
}

declare module '@storybook/addon-a11y/dist/index' {
  declare module.exports: any;
}

declare module '@storybook/addon-a11y/dist/register' {
  declare module.exports: any;
}

declare module '@storybook/addon-a11y/dist/shared/index' {
  declare module.exports: any;
}

declare module '@storybook/addon-a11y/manager' {
  declare module.exports: any;
}

declare module '@storybook/addon-a11y/register' {
  declare module.exports: any;
}

declare module '@storybook/addon-a11y/src/components/Panel' {
  declare module.exports: any;
}

declare module '@storybook/addon-a11y/src/components/Report/Elements' {
  declare module.exports: any;
}

declare module '@storybook/addon-a11y/src/components/Report/index' {
  declare module.exports: any;
}

declare module '@storybook/addon-a11y/src/components/Report/Info' {
  declare module.exports: any;
}

declare module '@storybook/addon-a11y/src/components/Report/Item' {
  declare module.exports: any;
}

declare module '@storybook/addon-a11y/src/components/Report/Rules' {
  declare module.exports: any;
}

declare module '@storybook/addon-a11y/src/components/Report/Tags' {
  declare module.exports: any;
}

declare module '@storybook/addon-a11y/src/components/Tabs' {
  declare module.exports: any;
}

declare module '@storybook/addon-a11y/src/index' {
  declare module.exports: any;
}

declare module '@storybook/addon-a11y/src/register' {
  declare module.exports: any;
}

declare module '@storybook/addon-a11y/src/shared/index' {
  declare module.exports: any;
}

// Filename aliases
declare module '@storybook/addon-a11y/dist/components/Panel.js' {
  declare module.exports: $Exports<'@storybook/addon-a11y/dist/components/Panel'>;
}
declare module '@storybook/addon-a11y/dist/components/Report/Elements.js' {
  declare module.exports: $Exports<'@storybook/addon-a11y/dist/components/Report/Elements'>;
}
declare module '@storybook/addon-a11y/dist/components/Report/index.js' {
  declare module.exports: $Exports<'@storybook/addon-a11y/dist/components/Report/index'>;
}
declare module '@storybook/addon-a11y/dist/components/Report/Info.js' {
  declare module.exports: $Exports<'@storybook/addon-a11y/dist/components/Report/Info'>;
}
declare module '@storybook/addon-a11y/dist/components/Report/Item.js' {
  declare module.exports: $Exports<'@storybook/addon-a11y/dist/components/Report/Item'>;
}
declare module '@storybook/addon-a11y/dist/components/Report/Rules.js' {
  declare module.exports: $Exports<'@storybook/addon-a11y/dist/components/Report/Rules'>;
}
declare module '@storybook/addon-a11y/dist/components/Report/Tags.js' {
  declare module.exports: $Exports<'@storybook/addon-a11y/dist/components/Report/Tags'>;
}
declare module '@storybook/addon-a11y/dist/components/Tabs.js' {
  declare module.exports: $Exports<'@storybook/addon-a11y/dist/components/Tabs'>;
}
declare module '@storybook/addon-a11y/dist/index.js' {
  declare module.exports: $Exports<'@storybook/addon-a11y/dist/index'>;
}
declare module '@storybook/addon-a11y/dist/register.js' {
  declare module.exports: $Exports<'@storybook/addon-a11y/dist/register'>;
}
declare module '@storybook/addon-a11y/dist/shared/index.js' {
  declare module.exports: $Exports<'@storybook/addon-a11y/dist/shared/index'>;
}
declare module '@storybook/addon-a11y/manager.js' {
  declare module.exports: $Exports<'@storybook/addon-a11y/manager'>;
}
declare module '@storybook/addon-a11y/register.js' {
  declare module.exports: $Exports<'@storybook/addon-a11y/register'>;
}
declare module '@storybook/addon-a11y/src/components/Panel.js' {
  declare module.exports: $Exports<'@storybook/addon-a11y/src/components/Panel'>;
}
declare module '@storybook/addon-a11y/src/components/Report/Elements.js' {
  declare module.exports: $Exports<'@storybook/addon-a11y/src/components/Report/Elements'>;
}
declare module '@storybook/addon-a11y/src/components/Report/index.js' {
  declare module.exports: $Exports<'@storybook/addon-a11y/src/components/Report/index'>;
}
declare module '@storybook/addon-a11y/src/components/Report/Info.js' {
  declare module.exports: $Exports<'@storybook/addon-a11y/src/components/Report/Info'>;
}
declare module '@storybook/addon-a11y/src/components/Report/Item.js' {
  declare module.exports: $Exports<'@storybook/addon-a11y/src/components/Report/Item'>;
}
declare module '@storybook/addon-a11y/src/components/Report/Rules.js' {
  declare module.exports: $Exports<'@storybook/addon-a11y/src/components/Report/Rules'>;
}
declare module '@storybook/addon-a11y/src/components/Report/Tags.js' {
  declare module.exports: $Exports<'@storybook/addon-a11y/src/components/Report/Tags'>;
}
declare module '@storybook/addon-a11y/src/components/Tabs.js' {
  declare module.exports: $Exports<'@storybook/addon-a11y/src/components/Tabs'>;
}
declare module '@storybook/addon-a11y/src/index.js' {
  declare module.exports: $Exports<'@storybook/addon-a11y/src/index'>;
}
declare module '@storybook/addon-a11y/src/register.js' {
  declare module.exports: $Exports<'@storybook/addon-a11y/src/register'>;
}
declare module '@storybook/addon-a11y/src/shared/index.js' {
  declare module.exports: $Exports<'@storybook/addon-a11y/src/shared/index'>;
}
