// flow-typed signature: 34af119f7a0a431c96067e7858444751
// flow-typed version: <<STUB>>/@storybook/addon-ondevice-notes_v^4.0.12/flow_v0.87.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@storybook/addon-ondevice-notes'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@storybook/addon-ondevice-notes' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@storybook/addon-ondevice-notes/dist/__tests__/index' {
  declare module.exports: any;
}

declare module '@storybook/addon-ondevice-notes/dist/index' {
  declare module.exports: any;
}

declare module '@storybook/addon-ondevice-notes/dist/register' {
  declare module.exports: any;
}

declare module '@storybook/addon-ondevice-notes/register' {
  declare module.exports: any;
}

declare module '@storybook/addon-ondevice-notes/src/__tests__/index' {
  declare module.exports: any;
}

declare module '@storybook/addon-ondevice-notes/src/index' {
  declare module.exports: any;
}

declare module '@storybook/addon-ondevice-notes/src/register' {
  declare module.exports: any;
}

// Filename aliases
declare module '@storybook/addon-ondevice-notes/dist/__tests__/index.js' {
  declare module.exports: $Exports<'@storybook/addon-ondevice-notes/dist/__tests__/index'>;
}
declare module '@storybook/addon-ondevice-notes/dist/index.js' {
  declare module.exports: $Exports<'@storybook/addon-ondevice-notes/dist/index'>;
}
declare module '@storybook/addon-ondevice-notes/dist/register.js' {
  declare module.exports: $Exports<'@storybook/addon-ondevice-notes/dist/register'>;
}
declare module '@storybook/addon-ondevice-notes/register.js' {
  declare module.exports: $Exports<'@storybook/addon-ondevice-notes/register'>;
}
declare module '@storybook/addon-ondevice-notes/src/__tests__/index.js' {
  declare module.exports: $Exports<'@storybook/addon-ondevice-notes/src/__tests__/index'>;
}
declare module '@storybook/addon-ondevice-notes/src/index.js' {
  declare module.exports: $Exports<'@storybook/addon-ondevice-notes/src/index'>;
}
declare module '@storybook/addon-ondevice-notes/src/register.js' {
  declare module.exports: $Exports<'@storybook/addon-ondevice-notes/src/register'>;
}
